"""Report generation utilities."""

from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Any, Dict

import pandas as pd
from jinja2 import Template

from ..analysis import metric_heatmap
from ..utils.io import ensure_dir


class StageReportWriter:
    def __init__(self, config: Dict[str, Any]):
        self.config = config
        self.template_path = Path("stage1_5/reporting/templates/stage1_5_report_template.md")

    def generate(self, decision, metrics_df: pd.DataFrame, metrics_path: Path) -> Dict[str, Any]:
        heatmap_dir = Path(self.config["analysis"]["heatmap_dir"])
        figure_accent = metric_heatmap(metrics_df, ["accent_f1"], heatmap_dir / "accent_f1.png", "Accent F1")
        figure_leak = metric_heatmap(metrics_df, ["leakage_a2s", "leakage_s2a"],
                                     heatmap_dir / "leakage.png", "Leakage")

        report_path = Path(self.config["paths"]["report"])
        ensure_dir(report_path.parent)

        context = {
            "dataset_name": Path(self.config["paths"]["manifest"]).name,
            "date": datetime.utcnow().strftime("%Y-%m-%d"),
            "config_path": str(Path(self.config.get("config_path", "config/stage1_5.yaml")).resolve()),
            "metrics": metrics_df.to_dict("records"),
            "best_layer": decision.label or "N/A",
            "decision": decision.status,
            "rationale": decision.rationale,
            "notes": "Auto-generated by Stage 1.5 pipeline.",
        }

        template = Template(self.template_path.read_text())
        report_path.write_text(template.render(**context))

        return {
            "decision": decision.status,
            "best_layer": decision.label,
            "metrics_path": str(metrics_path),
            "report_path": str(report_path),
            "figures": {
                "accent": str(figure_accent),
                "leakage": str(figure_leak),
            },
            "rationale": decision.rationale,
        }
